name: aof # you probably want to 'snapcraft register <name>'
version: '0.2.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Redis appendonly file filter # 79 char long summary
description: |
  Redis appendonly file filter
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
parts:
  aof:
    plugin: rust
    source: .
apps:
  aof:
    command: env PATH=$SNAP/bin:$PATH aof
